class Mail{
public static void main(String[] args){
String kavana="kavanasnaik@gmail.com";
String rohit="rohit.sharma@gmail.com";
String pallavi="pallavigh34@gmail.com";
String divya="deghtyy3457@gmail.com";
String sangeeta="sangeetha22@gmail.com";
String arjun="arjunsingh@gmail.com";
String raj="rajmehta@gmail.com";
String priya="priyaagarwal@gmail.com";
String sania="saniakhan@gmail.com";
String kiccha="kicchasudeep@gmail.com";
String hith="hitheshi901@gmail.com";
String ganesh="ganeshty456@gmail.com";
String thilak="thilaknaikty8@gmail.com";
String suresh="sureshnaikb67@gmail.com";
String prema="preman67@gmail.com";
String[] email={kavana,rohit,pallavi,divya,sangeeta,arjun,raj,priya,sania,kiccha,hith,ganesh,thilak,suresh,prema};
int totalmails=email.length;
		String ref=email[0];
		String ref1=email[1];
		String ref2=email[2];
		String ref3=email[3];
		String ref4=email[4];
		String ref5=email[5];
		String ref6=email[6];
		String ref7=email[7];
		String ref8=email[8];
		String ref9=email[9];
		String ref10=email[10];
		String ref11=email[11];
		String ref12=email[12];
		String ref13=email[13];
		String ref14=email[14];
		System.out.println(ref);
		System.out.println(ref1);
		System.out.println(ref2);
		System.out.println(ref3);
		System.out.println(ref4);
		System.out.println(ref5);
		System.out.println(ref6);
		System.out.println(ref7);
		System.out.println(ref8);
		System.out.println(ref9);
		System.out.println(ref10);
		System.out.println(ref11);
		System.out.println(ref12);
		System.out.println(ref13);
		System.out.println(ref14);
    }
}
